server:
  port: 7002

spring:
  application:
    name:  cloud_eureka_server7002

eureka:
  instance:
    hostname: eureka7002.com   #eureka服务端的实例名称
  client:
    # false表示不会向注册中心注册自己
    register-with-eureka: true
    # false表示自己就是注册中心，职责就是维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
