server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment8001
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://simon2020.mysql.rds.aliyuncs.com:3306/clouddemo2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: simon
    password: Gem2015123163
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.simon.clouddemo.domain

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
